# Discovery Server Access
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
  instance:
    preferIpAddress: true

service:
  authserver:
    serviceID: AUTH-SERVICE

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000